import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "../../components/SideBar";
import NewChat from "../../components/NewChat";
import SessionProvider from "../../components/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]";
import Login from "../../components/Login";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "LawLens",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>

          {!session ?(
            <Login />
          ) : (
            <div className="flex h-full">
            <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[15rem]">
            <SideBar />
            </div>
          
  
         <div className="bg-gray-200 flex-1 "> {children}
         </div>
          </div>
          )
        }
       
        </SessionProvider>
        </body>
    </html>
  );
}
